// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjInv.Infrastructure.Data;

#nullable disable

namespace ProjInv.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjInv.Domain.Entities.Investidor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Investidores", (string)null);
                });

            modelBuilder.Entity("ProjInv.Domain.Entities.Investimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InvestidorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ValorInicial")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvestidorId");

                    b.ToTable("Investimentos", (string)null);
                });

            modelBuilder.Entity("ProjInv.Domain.Entities.Retirada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataRetirada")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Impostos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("InvestimentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ValorBruto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorLiquido")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvestimentoId")
                        .IsUnique();

                    b.ToTable("Retiradas", (string)null);
                });

            modelBuilder.Entity("ProjInv.Domain.Entities.Investimento", b =>
                {
                    b.HasOne("ProjInv.Domain.Entities.Investidor", "Investidor")
                        .WithMany("Investimentos")
                        .HasForeignKey("InvestidorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Investidor");
                });

            modelBuilder.Entity("ProjInv.Domain.Entities.Retirada", b =>
                {
                    b.HasOne("ProjInv.Domain.Entities.Investimento", "Investimento")
                        .WithOne("Retirada")
                        .HasForeignKey("ProjInv.Domain.Entities.Retirada", "InvestimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Investimento");
                });

            modelBuilder.Entity("ProjInv.Domain.Entities.Investidor", b =>
                {
                    b.Navigation("Investimentos");
                });

            modelBuilder.Entity("ProjInv.Domain.Entities.Investimento", b =>
                {
                    b.Navigation("Retirada");
                });
#pragma warning restore 612, 618
        }
    }
}
